import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { LIMIT, VERSION, type Project } from './model.js';
import { byId, buildIndex } from './indexes.js';
import { compiledArtifacts } from './compiled.js';
import { declarationDigest, json } from './serialization.js';
import { localPath } from './paths.js';

export function summarize(project: Project) {
  const { graph } = project;
  return {
    graphId: graph.id, title: graph.title, scope: graph.description, limitation: LIMIT,
    nodes: graph.nodes.length, relationships: graph.relationships.length, modules: graph.modules?.length ?? 0,
    statuses: Object.fromEntries(['proposed', 'implemented', 'unresolved'].map(status => [status, graph.nodes.filter(node => node.status === status).length])),
    unresolved: [...graph.nodes, ...graph.relationships].filter(item => item.status === 'unresolved')
      .map(item => ({ id: item.id, description: item.description })).sort(byId),
  };
}
/** Small human briefing; full data stays in machine-readable indexes and targeted context. */
export function renderArtifacts(project: Project): Record<string, string> {
  const { graph, config } = project;
  // Generate from canonical declarations, never from a loaded cache.
  const index = buildIndex(graph, config.graph);
  const fingerprint = declarationDigest(graph, config);
  const summary = summarize(project);
  const excerpt = (text: string): string => text.length > 240 ? text.slice(0, 237) + '...' : text;
  const modules = (graph.modules ?? []).slice(0, 12).map(module => `- **${excerpt(module.name)}** (\`${module.id}\`): ${excerpt(module.description)}`).join('\n');
  const questions = summary.unresolved.slice(0, 10).map(item => `- \`${item.id}\`: ${excerpt(item.description)}`).join('\n');
  const guidance = `# ${excerpt(graph.title)}\n\nThis briefing helps you find the recorded design before making a change. The complete authored graph is \`${config.graph}\`.\n\n${LIMIT}\n\n## Scope\n\n${excerpt(graph.description)}\n\nThe graph records ${summary.nodes} ideas, ${summary.relationships} relationships, and ${summary.modules} logical modules in one file.\n\n## Find the relevant design\n\nUse the project's installed \`ag context --id <id>\` or \`ag context --file <path>\`. You can also use \`--module <id>\`, \`--guardrail <id>\`, or \`--query <text>\`. Results include incoming and outgoing relationships. Read the referenced files and keep open questions visible.\n\nContext is limited to 60 nodes and 120 examined relationships by default. A shortened result explicitly says it is incomplete. Narrow the lookup or raise \`--max-nodes\` and \`--max-relationships\` when needed. This briefing is an overview, not the full architecture.\n\n## Logical modules\n\n${modules || 'No logical modules are declared.'}${summary.modules > 12 ? '\n\nMore modules exist; use the graph or a module lookup.' : ''}\n\n## Open questions\n\n${questions || 'No unresolved decisions are recorded.'}${summary.unresolved.length > 10 ? '\n\nMore unresolved records exist; use ag summary for the complete list.' : ''}\n\n## Keep the record useful\n\nWhen the design changes, update the single graph alongside the code. Proposed work is a plan; unresolved work still needs a decision. Run application tests, then \`ag validate\`, \`ag generate\`, and \`ag check\`. Regenerate this briefing instead of editing it directly.\n\nGenerated by AG ${VERSION}. Declaration fingerprint: \`${fingerprint}\`. This identifies the records, not evidence of correct behavior.\n`;
  return {
    ...compiledArtifacts(index, graph.id, fingerprint),
    'guidance.md': guidance,
    'summary.json': json({ artifactVersion: '2', toolVersion: VERSION, declarationDigest: fingerprint, ...summary }),
  };
}
export function syncArtifacts(project: Project, { check = false }: { check?: boolean } = {}): { drift: string[]; limitation: string } {
  const artifacts = renderArtifacts(project);
  const targets = Object.entries(artifacts).map(([name, body]) => ({ path: localPath(project.root, `${project.config.generated}/${name}`), body, name }));
  const drift = targets.filter(({ path, body }) => !existsSync(path) || readFileSync(path, 'utf8') !== body).map(target => target.name);
  if (!check) for (const { path, body } of targets) { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, body); }
  return { drift, limitation: LIMIT };
}
